# Generated by Django 3.2 on 2022-09-02 03:24

from django.db import migrations, models
import django.utils.timezone
import snooperspy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
                ('countries', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.IntegerField(default=0)),
                ('female', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This refer to the name of the product', max_length=250)),
                ('kind_ads', models.CharField(blank=True, help_text='FaceBook, Instagram, tiktok...', max_length=250, null=True)),
                ('media_ads', models.CharField(blank=True, help_text='Video, Photo, both', max_length=250, null=True)),
                ('image', models.ImageField(default='products/default.jpg', upload_to=snooperspy.models.upload_to, verbose_name='Image')),
                ('ads_image', models.ImageField(default='products/default.jpg', upload_to=snooperspy.models.upload_to, verbose_name='Image')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, help_text='First time we saw this ads')),
                ('we_found', models.DateTimeField(default=django.utils.timezone.now, help_text='This ads wa created between')),
                ('likes', models.IntegerField(default=0, help_text='Amount of likes generated')),
                ('product_cost', models.IntegerField(default=0, help_text='Price pay to buy this product')),
                ('selling_price', models.IntegerField(default=0, help_text='Price you can sell this product')),
                ('profit_margin', models.IntegerField(default=0, help_text='Profit you get from this product')),
                ('number_of_suppliers', models.IntegerField(default=0, help_text='Number of suppliers we get for this product')),
                ('number_of_comment', models.IntegerField(default=0, help_text='Number of comment we get for this product')),
                ('number_of_likes', models.IntegerField(default=0, help_text='Number of likes we get for this product')),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='SellingOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sotre_location', models.CharField(blank=True, max_length=200, null=True)),
                ('sotre_intelligence', models.CharField(blank=True, max_length=200, null=True)),
                ('sotre_links', models.CharField(blank=True, max_length=200, null=True)),
                ('sotre_ads', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'SellingOn',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers_location', models.CharField(blank=True, max_length=200, null=True)),
                ('suppliers_links', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
