# Generated by Django 3.2 on 2022-08-24 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import snooperspy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CompetitorMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
                ('competiton', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'CompetitorMeters',
            },
        ),
        migrations.CreateModel(
            name='FacebookTargetArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Industry', models.CharField(blank=True, max_length=200, null=True)),
                ('Entertainment', models.CharField(blank=True, max_length=200, null=True)),
                ('Family_relationships', models.CharField(blank=True, max_length=200, null=True)),
                ('Fitness_wellness', models.CharField(blank=True, max_length=200, null=True)),
                ('Food_drink', models.CharField(blank=True, max_length=200, null=True)),
                ('Hobbies_activities', models.CharField(blank=True, max_length=200, null=True)),
                ('Shopping_fashion', models.CharField(blank=True, max_length=200, null=True)),
                ('Sports_outdoors', models.CharField(blank=True, max_length=200, null=True)),
                ('Technology', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'FacebookTargetArea',
            },
        ),
        migrations.CreateModel(
            name='OrdersStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_last_6_months', models.IntegerField(default=0)),
                ('Total_last_30_days', models.IntegerField(default=0)),
                ('Total_last_14_days', models.IntegerField(default=0)),
                ('Total_last_7_days', models.IntegerField(default=0)),
                ('daily_approximation', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'OrdersStatistics',
            },
        ),
        migrations.CreateModel(
            name='ProductInsights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200)),
                ('Product_Breakthrough', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'ProductInsights',
            },
        ),
        migrations.CreateModel(
            name='ProductInsightsRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200)),
                ('Product_Breakthrough_rating', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Product_Breakthrough_rating',
            },
        ),
        migrations.CreateModel(
            name='SellingOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sotre_location', models.CharField(blank=True, max_length=200, null=True)),
                ('sotre_intelligence', models.CharField(blank=True, max_length=200, null=True)),
                ('sotre_links', models.CharField(blank=True, max_length=200, null=True)),
                ('sotre_ads', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'SellingOn',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers_location', models.CharField(blank=True, max_length=200, null=True)),
                ('suppliers_links', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='TopCustomerCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
                ('competiton', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'TopCustomerCountries',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(default='products/default.jpg', upload_to=snooperspy.models.upload_to, verbose_name='Image')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('we_found', models.DateTimeField(default=django.utils.timezone.now)),
                ('orders', models.IntegerField(default=0)),
                ('product_cost', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('profit_margin', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('number_of_suppliers', models.IntegerField(default=0)),
                ('number_of_store_selling', models.IntegerField(default=0)),
                ('view_facebook_ads', models.CharField(blank=True, max_length=250, null=True)),
                ('view_on_amazon', models.CharField(blank=True, max_length=250, null=True)),
                ('view_on_youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('view_tiktok_ads', models.CharField(blank=True, max_length=250, null=True)),
                ('view_pinterest_ads', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snooperspy_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.category')),
                ('competitor_meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.competitormeter')),
                ('facebook_target_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.facebooktargetarea')),
                ('orders_statistics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.ordersstatistics')),
                ('product_insights', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.productinsights')),
                ('product_insights_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.productinsightsrating')),
                ('selling_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.sellingon')),
                ('suppliers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.suppliers')),
                ('top_customer_countries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.topcustomercountries')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
