# Generated by Django 3.2 on 2022-09-02 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snooperspy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snooperspy_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.countries'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.gender'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.sellingon'),
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snooperspy.suppliers'),
        ),
    ]
