# Generated by Django 3.2 on 2022-08-25 19:12

from django.db import migrations, models
import snooperspy.models


class Migration(migrations.Migration):

    dependencies = [
        ('snooperspy', '0002_auto_20220825_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ads_image',
            field=models.ImageField(default='products/default.jpg', upload_to=snooperspy.models.upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_comment',
            field=models.IntegerField(default=0, help_text='Number of comment we get for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_likes',
            field=models.IntegerField(default=0, help_text='Number of likes we get for this product'),
        ),
    ]
